version: '3.8'

services:
  frontend:
    build: .
    container_name: front_despacho
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge