- name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          use_insecure_cipher: true
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/front-despacho:latest
            docker stop front_despacho || true
            docker rm front_despacho || true
            docker run -d \
              --name front_despacho \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/front-despacho:latest